"""2025112511_QSM_004

Revision ID: 938080744ade
Revises: ea4584a457f9
Create Date: 2025-11-28 11:41:53.527301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '938080744ade'
down_revision: Union[str, Sequence[str], None] = 'ea4584a457f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operations', sa.Column('code', sa.Text(), nullable=False), schema='qsmith_service')
    op.add_column('operations', sa.Column('description', sa.Text(), nullable=True), schema='qsmith_service')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('operations', 'description', schema='qsmith_service')
    op.drop_column('operations', 'code', schema='qsmith_service')
    # ### end Alembic commands ###
