"""2025111717_QSM_003

Revision ID: ea4584a457f9
Revises: 
Create Date: 2025-11-21 10:48:37.047206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea4584a457f9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table('json_payloads',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('json_type', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('modified_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='qsmith_service'
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logs',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('subject_type', sa.Text(), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('level', sa.Text(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='qsmith_service'
    )
    op.create_table('operations',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('operation_type', sa.Text(), nullable=False),
    sa.Column('configuration_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='qsmith_service'
    )
    op.create_table('queues',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('broker_id', sa.Text(), nullable=False),
    sa.Column('configuration_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='qsmith_service'
    )
    op.create_table('scenarios',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='qsmith_service'
    )
    op.create_table('steps',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('step_type', sa.Text(), nullable=False),
    sa.Column('configuration_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='qsmith_service'
    )
    op.create_table('scenario_steps',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('scenario_id', sa.Text(), nullable=False),
    sa.Column('step_id', sa.Text(), nullable=False),
    sa.Column('order', sa.Numeric(), nullable=False),
    sa.Column('on_failure', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.ForeignKeyConstraint(['scenario_id'], ['qsmith_service.scenarios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['step_id'], ['qsmith_service.steps.id'], ),
    schema='qsmith_service'
    )
    op.create_table('step_operations',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('scenario_step_id', sa.Text(), nullable=False),
    sa.Column('operation_id', sa.Text(), nullable=False),
    sa.Column('order', sa.Numeric(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.ForeignKeyConstraint(['operation_id'], ['qsmith_service.operations.id'], ),
    sa.ForeignKeyConstraint(['scenario_step_id'], ['qsmith_service.scenario_steps.id'], ondelete='CASCADE'),
    schema='qsmith_service'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('step_operations', schema='qsmith_service')
    op.drop_table('scenario_steps', schema='qsmith_service')
    op.drop_table('steps', schema='qsmith_service')
    op.drop_table('scenarios', schema='qsmith_service')
    op.drop_table('queues', schema='qsmith_service')
    op.drop_table('operations', schema='qsmith_service')
    op.drop_table('logs', schema='qsmith_service')
    op.drop_table('json_payloads', schema='qsmith_service')
    # ### end Alembic commands ###
